name: call-custom-py-gha
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run action

      # Put your action repo here
      uses: dptcs/custom-py-gha@main
      # Put an example of your mandatory inputs here
      with:
        myInput: world
