name: Called With Exit WF

on:
  workflow_call:

jobs:
  job1a-exit-1:
    runs-on: ubuntu-latest
    steps:
       - run: exit 1 
       - run: sleep 5
       
  job1b-after-exit1:
    needs: job1a-exit-1
    runs-on: ubuntu-latest
    steps:
    - run: date
    - run: sleep 5

  
  job2a-simple-wf:
    runs-on: ubuntu-latest
    steps:
    - run: date
    - run: sleep 5
    
  job2b-after-simple:
    needs: job2a-simple-wf
    runs-on: ubuntu-latest
    steps:
    - run: date
