name: Called WF

on:
  workflow_call:

jobs:
  job1a-true-condition:
    runs-on: ubuntu-latest
    if: ${{  'a' == 'a' }}
    steps:
       - run: date
       - run: sleep 5
       
  job1b-true-condition:
    needs: job1a-true-condition
    if: ${{  'a' == 'a' }}
    runs-on: ubuntu-latest
    steps:
    - run: date
    - run: sleep 5
  
  job1c-true-condition:
    needs: job1a-true-condition
    if: ${{  'a' == 'a' }}
    runs-on: ubuntu-latest
    steps:
    - run: date
    - run: sleep 5
    
  job1d-true-condition:
    needs: job1c-true-condition
    if: ${{  'a' == 'a' }}
    runs-on: ubuntu-latest
    steps:
    - run: date
  
  job2a-true-condition:
    if: ${{  'a' == 'a' }}
    runs-on: ubuntu-latest
    steps:
    - run: date
    - run: sleep 5
    
  job2b-false-condition:
    needs: job2a-true-condition
    if: ${{  'a' == 'b' }}
    runs-on: ubuntu-latest
    steps:
    - run: date
